apiVersion: v1
kind: Secret
metadata:
  name: newtarr-secret
  namespace: media
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:bte992qrzr+4ieDoOY77/AMnleQW5oXNPQqilYTb99KRPDrbb5b6oKQ6c9sGTDEjKJD8Jx5qQrVJcU7In2qn6g==,iv:/gV8Bx4vE67Y8f+PlVQUc74h+KWbNbOweDsassnMp/U=,tag:/QixcbviSeyXrp9Q2+1qEw==,type:str]
sops:
  age:
    - recipient: age1metxlry78wefrmm5ny2zjavtucsmdvw2r3ctexu6h05ak4x2vc7qa02drd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WUJqd0Z3bVk0UHd1LzV2
        cFZYemxPRGViVjJhcVRWSDVmYUZoT2VYUldFCjhLNmhIQ20xYU14UXZRZmdlUzJL
        N3Fha3BqSUppTzRFeHBHNElKMDNMREUKLS0tIDl5S1pUR3Z4ZkZhYkdsNlZlN09w
        UTdmQjN1KzR2NXhmc0FqNVpmRjZxMlEKa4loDdpb5i3jgtQb8qIrETyNrqzvA/4w
        SE3htkMqXpFBkQk8ijzSGxkPjXnumEgieGCn9K5uzVTPMuBebY4zqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-25T03:42:05Z"
  mac: ENC[AES256_GCM,data:FzY42nECT5IRAOMFNjEyclpUeSl1Rraylnv18RLsVlqzahKOOOHFIy968sJesrteWr76DnRqJ21br2LPK1CdDZyU9wKTSyBD+w6r3uAWdMTW1bHzlBzvnPaRB/18D0QFqChTuKvEGWrlfIGnldpBAnImLI7CdNgRfdkCxEa5fSA=,iv:t9LHkUpgQTbaVNGszH2hwj7Qfw0dYfXNY0MXxXj3EKQ=,tag:um+bfDWemy7KKxh0rGnkjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
