-- Generated by scripts/hindsight-backlog-function.py --write; do not edit.
-- Not referenced by any Kustomization: nothing applies this file yet.
-- Qualified for ghcr.io/vectorize-io/hindsight-api:0.9.2@sha256:7b14a1f4062252992d0176758753615e0a2071d9a269995be007be223ab01812
-- at Alembic head d1e2f3a4b5c6. Apply as the hindsight role (SET ROLE
-- hindsight is enough); the guards refuse any other owner and roll back on drift.
BEGIN;
SET LOCAL search_path = pg_catalog, pg_temp;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';
DO $guard$
BEGIN
 IF current_user <> 'hindsight' OR (SELECT rolsuper FROM pg_roles WHERE rolname = current_user) THEN
  RAISE EXCEPTION 'apply as the non-superuser hindsight role';
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'hindsight_backlog_metrics' AND NOT rolsuper
                AND NOT rolcreaterole AND NOT rolcreatedb AND NOT rolreplication AND NOT rolbypassrls)
    OR EXISTS (SELECT 1 FROM pg_auth_members m JOIN pg_roles r ON r.oid IN (m.member, m.roleid)
               WHERE r.rolname = 'hindsight_backlog_metrics') THEN
  RAISE EXCEPTION 'hindsight_backlog_metrics must exist with no extra authority, members or memberships';
 END IF;
 IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'hindsight_metrics' AND nspowner <> 'hindsight'::regrole)
    OR EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
               WHERE n.nspname = 'hindsight_metrics')
    OR EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
               WHERE n.nspname = 'hindsight_metrics')
    OR EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
               WHERE n.nspname = 'hindsight_metrics' AND (p.proname <> 'runnable_backlog' OR p.pronargs <> 0
                     OR p.proowner <> 'hindsight'::regrole)) THEN
  RAISE EXCEPTION 'hindsight_metrics holds a relation, type or function this file did not generate';
 END IF;
END
$guard$;
CREATE SCHEMA IF NOT EXISTS hindsight_metrics AUTHORIZATION hindsight;
CREATE OR REPLACE FUNCTION hindsight_metrics.runnable_backlog()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SECURITY DEFINER
 SET search_path = pg_catalog, pg_temp
AS $function$
BEGIN
 -- plpgsql binds relations when the body runs and records no pg_depend rows on
 -- them, so upstream migrations stay unblocked. A shape or revision the predicate
 -- was not qualified for is reported as the fixed unknown, never as zero.
 IF (SELECT count(*) FROM pg_class WHERE relkind IN ('r', 'p') AND oid IN (to_regclass('public.async_operations'),
       to_regclass('public.banks'), to_regclass('public.alembic_version'))) <> 3
    OR (SELECT count(*) FROM pg_attribute WHERE attrelid = to_regclass('public.async_operations')
          AND attnum > 0 AND NOT attisdropped AND attname = ANY (ARRAY['operation_id', 'bank_id', 'operation_type', 'status', 'task_payload', 'serialization_key', 'created_at', 'next_retry_at', 'worker_id']::name[])) <> 9
    OR NOT EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = to_regclass('public.banks')
          AND attnum > 0 AND NOT attisdropped AND attname = 'bank_id')
    OR (SELECT count(*) FROM public.alembic_version) <> 1
    OR NOT EXISTS (SELECT 1 FROM public.alembic_version WHERE version_num = 'd1e2f3a4b5c6') THEN
  RAISE EXCEPTION USING ERRCODE = 'HSB01', MESSAGE = 'hindsight backlog unknown';
 END IF;
 RETURN (
WITH ops AS NOT MATERIALIZED (
 SELECT operation_id, bank_id, operation_type, status, task_payload, serialization_key,
        created_at, next_retry_at, worker_id
 FROM public.async_operations
), bank_ids AS NOT MATERIALIZED (
 SELECT bank_id FROM public.banks
), active AS MATERIALIZED (
 SELECT o.bank_id, o.operation_type, o.status, o.worker_id, o.created_at, o.next_retry_at,
        o.status = 'pending' AND o.task_payload IS NULL AS payload_null,
        o.status = 'pending' AND o.task_payload IS NOT NULL AND o.next_retry_at > now() AS deferred,
        o.status = 'pending' AND o.task_payload IS NOT NULL
          AND (o.next_retry_at IS NULL OR o.next_retry_at <= now()) AS due,
        o.status = 'pending' AND o.task_payload IS NOT NULL
          AND (o.next_retry_at IS NULL OR o.next_retry_at <= now())
          AND (o.operation_type NOT IN ('graph_maintenance', 'consolidation') OR NOT EXISTS (
            SELECT 1 FROM ops bank_peer
            WHERE bank_peer.bank_id = o.bank_id
              AND bank_peer.operation_type = o.operation_type
              AND (bank_peer.status = 'processing'
                   OR (bank_peer.status = 'pending'
                       AND bank_peer.task_payload IS NOT NULL
                       AND (bank_peer.next_retry_at IS NULL OR bank_peer.next_retry_at <= now())
                       AND (bank_peer.created_at < o.created_at
                            OR (bank_peer.created_at = o.created_at
                                AND bank_peer.operation_id < o.operation_id))))))
          AND (o.operation_type = 'consolidation' OR o.serialization_key IS NULL OR NOT EXISTS (
            SELECT 1 FROM ops doc_peer
            WHERE doc_peer.bank_id = o.bank_id
              AND doc_peer.serialization_key = o.serialization_key
              AND (doc_peer.status = 'processing'
                   OR (doc_peer.status = 'pending'
                       AND doc_peer.task_payload IS NOT NULL
                       AND (doc_peer.next_retry_at IS NULL OR doc_peer.next_retry_at <= now())
                       AND (doc_peer.created_at < o.created_at
                            OR (doc_peer.created_at = o.created_at
                                AND doc_peer.operation_id < o.operation_id)))))) AS runnable
 FROM ops o
 WHERE o.status IN ('pending', 'processing')
), grouped AS (
 SELECT bank_id, operation_type,
        count(*) FILTER (WHERE status = 'pending') AS pending,
        count(*) FILTER (WHERE payload_null) AS payload_null_pending,
        count(*) FILTER (WHERE deferred) AS deferred,
        count(*) FILTER (WHERE due) AS due,
        count(*) FILTER (WHERE runnable) AS runnable,
        count(*) FILTER (WHERE due AND NOT runnable) AS serialization_blocked,
        count(*) FILTER (WHERE status = 'processing') AS processing,
        count(*) FILTER (WHERE status = 'pending' AND worker_id IS NOT NULL) AS assigned_pending,
        count(*) FILTER (WHERE runnable AND worker_id IS NOT NULL) AS assigned_runnable,
        count(*) FILTER (WHERE runnable AND created_at > now()) AS future_created_runnable,
        CASE WHEN bool_or(runnable) THEN GREATEST(0, EXTRACT(EPOCH FROM now() - min(created_at) FILTER (WHERE runnable)))
        END AS runnable_oldest_task_age_seconds,
        EXTRACT(EPOCH FROM now() - min(next_retry_at) FILTER (WHERE runnable)) AS runnable_oldest_retry_lateness_seconds
 FROM active GROUP BY bank_id, operation_type
), listed AS (
 SELECT bank_id, true AS registered FROM bank_ids
 UNION
 SELECT g.bank_id, false FROM grouped g WHERE NOT EXISTS (SELECT 1 FROM bank_ids b WHERE b.bank_id = g.bank_id)
)
SELECT (CASE WHEN (SELECT count(*) FROM grouped) > 256 OR (SELECT count(*) FROM listed) > 256
 THEN json_build_object('capacity_exceeded', true)
 ELSE json_build_object('capacity_exceeded', false,
  'observed_at', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"+00:00"'),
  'banks', COALESCE((SELECT json_agg(json_build_object('bank', bank_id, 'registered', registered)) FROM listed), '[]'::json),
  'groups', COALESCE((SELECT json_agg(json_build_object('bank', bank_id, 'operation_type', operation_type,
    'pending', pending, 'payload_null_pending', payload_null_pending, 'deferred', deferred, 'due', due,
    'runnable', runnable, 'serialization_blocked', serialization_blocked, 'processing', processing,
    'assigned_pending', assigned_pending, 'assigned_runnable', assigned_runnable,
    'future_created_runnable', future_created_runnable, 'runnable_oldest_task_age_seconds', runnable_oldest_task_age_seconds,
    'runnable_oldest_retry_lateness_seconds', runnable_oldest_retry_lateness_seconds)) FROM grouped), '[]'::json))
END)::jsonb
 );
EXCEPTION WHEN OTHERS THEN
 -- Fixed code and message only: no source error text or row value escapes.
 -- Cancellation (statement_timeout) is not OTHERS and still surfaces as 57014.
 RAISE EXCEPTION USING ERRCODE = 'HSB01', MESSAGE = 'hindsight backlog unknown';
END
$function$;
REVOKE ALL ON SCHEMA hindsight_metrics FROM PUBLIC;
REVOKE ALL ON FUNCTION hindsight_metrics.runnable_backlog() FROM PUBLIC;
GRANT USAGE ON SCHEMA hindsight_metrics TO hindsight_backlog_metrics;
GRANT EXECUTE ON FUNCTION hindsight_metrics.runnable_backlog() TO hindsight_backlog_metrics;
DO $verify$
DECLARE
 fn oid := to_regprocedure('hindsight_metrics.runnable_backlog()');
BEGIN
 IF fn IS NULL
    OR (SELECT nspowner FROM pg_namespace WHERE nspname = 'hindsight_metrics') <> 'hindsight'::regrole
    OR ARRAY(SELECT a::text FROM pg_namespace n, unnest(n.nspacl) a WHERE n.nspname = 'hindsight_metrics'
             ORDER BY a::text COLLATE "C") <> ARRAY['hindsight=UC/hindsight', 'hindsight_backlog_metrics=U/hindsight']
    OR ARRAY(SELECT a::text FROM pg_proc p, unnest(p.proacl) a WHERE p.oid = fn
             ORDER BY a::text COLLATE "C") <> ARRAY['hindsight=X/hindsight', 'hindsight_backlog_metrics=X/hindsight']
    OR NOT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid = p.prolang
                   WHERE p.oid = fn AND p.proowner = 'hindsight'::regrole AND p.prosecdef AND p.provolatile = 's'
                     AND NOT p.proretset AND p.prorettype = 'jsonb'::regtype AND l.lanname = 'plpgsql'
                     AND p.proconfig = ARRAY['search_path=pg_catalog, pg_temp'])
    OR EXISTS (SELECT 1 FROM pg_depend WHERE classid = 'pg_proc'::regclass AND objid = fn
               AND refclassid = 'pg_class'::regclass) THEN
  RAISE EXCEPTION 'hindsight_metrics.runnable_backlog ownership, ACL or attributes are not as generated';
 END IF;
END
$verify$;
COMMIT;
