apiVersion: v1
kind: ConfigMap
metadata:
  name: obsidian-mcp-registry-v2
  namespace: notes
immutable: true
data:
  registry.json: |
    {
      "version": 2,
      "clients": [
        "antigravity",
        "claude",
        "codex",
        "opencode"
      ],
      "owner": {
        "check_url": "http://authentik-server.security.svc.cluster.local/outpost.goauthentik.io/auth/nginx",
        "origin": "https://obsidian.homelab0.org",
        "owner_ids": [
          "cf7f9af450fffb506f4098538e8db2fe53a58c2960ab923fda9c8dff002ddbc7"
        ]
      }
    }
