apiVersion: v1
kind: Secret
metadata:
  name: obsidian-mcp-secret
  namespace: notes
type: Opaque
stringData:
  CLIENT_CLAUDE_CODE: ENC[AES256_GCM,data:dl7hrTuvRWv5f1IBkiOXRWK7oCbIUJKWvZsRE8SgjqPeC1me03NeJ7HUe57v3nfSIpfd4yNsxSw7NJ7pJjw8ZQ==,iv:LNCeLc0RGvgPqsSpkXRlFc+Jef6pDJMEt/2sSpGLj1o=,tag:E4KNbDYpJF0P96wYh/tlhw==,type:str]
  CLIENT_CODEX: ENC[AES256_GCM,data:8jJws7qw/AF/6CQanUG06F7VW3vFHcX60cefGD13KjSw45sIEOKd/SDOB0Y18w/xA+lJAFN/v69K14n2B9cWCA==,iv:XjVcuxKFhNoRFD8+ZaAf1X+pYI5lsScFbzu+JNekPsM=,tag:DNAAIoM9DeIprAnjJ4Q/lw==,type:str]
  CLIENT_OPENCODE: ENC[AES256_GCM,data:3gbcJrLUD1XfDb7tPtVG7yLtB682WGwfO+OVTZhKPat1sCdr6Vkw23qJkFThWT7YPra+e6LyDb8g/tjOKvRIpA==,iv:u/hkCzK8E0D/py2aIUUxGOaqA354N977VZD+iLJ61Eo=,tag:6bdU2UcEuA4ZNSoqlDR2dg==,type:str]
  CLIENT_ANTIGRAVITY: ENC[AES256_GCM,data:rgubn3zeSoLNAMHLpdSM3Rjxx8L5uJ4rUx4uU5t15lbvF1RoTwa+T/kty7bfEfZL3a7F4NVIGApI5nPB8yTCuA==,iv:ZD7QzW1/ca8Upv3dNlO2WdZMB2WhYLLkVUHn2q/+L9k=,tag:AqiFtefjTK0XjuGFzH5zeg==,type:str]
sops:
  age:
    - recipient: age1metxlry78wefrmm5ny2zjavtucsmdvw2r3ctexu6h05ak4x2vc7qa02drd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRGRVSVZEaitMU3p1M0to
        S0s0Um01VTNBdkZnVTNZOC9xWnlSUXFNTzBvCnRDSXFrOVVFbER5dzZ3N1QwL2s3
        S2dURHE1SDdUOU1mWFlnYnl1TGxWQ1kKLS0tIGEwdWlqekJEdzZwbllpN1EreXVW
        T0FBcDRueWplTFRKMEt6aTByelRmeEkKcNDRxykF6hvQipr8H2Pf3S4SbXzDh+ay
        gU6BOdTsGL9NVfF/bdjtWsC8QUiFXOBEXovAZykKAjKMKMY8wqF5cw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-10-01T16:31:02Z"
  mac: ENC[AES256_GCM,data:XSy471mBJo5R7lWbK1gF65R66FXPzqHs6dRWU4eD6vACc2k0e59eEbGm0DddXFoXr7GE2D6Lf2pItD/OF1zM4fX2y33D9PmhciVjCVrrwhE+QxcMDNLx39fe8MuLhnQe/MLNPniYt59AizqOXMR7fsTIJz2/FllXxnV3M64LMyQ=,iv:xi0eUT3qKIWsm36opMdl6ng5WJChNAzIHnHJE9rB39s=,tag:awjCPNjkeX3fMvlRzOU1JA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
