---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flagger-pilot

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./flagger/ks.yaml
  - ./loadtester/ks.yaml
  - ./pilot-source/ks.yaml
  - ./pilot-app/ks.yaml
