# Entra ID app registration "authentik" (tenant homelab0org), used by the
# entra-id OAuth source. Client secret expires 2027-10-04T11:17:48Z; rotate before then.
apiVersion: v1
kind: Secret
metadata:
  name: authentik-entra
  namespace: security
type: Opaque
stringData:
  AUTHENTIK_ENTRA_TENANT_ID: ENC[AES256_GCM,data:AZQSi1TV25hmhDxF+YF4qiyy8RKn3+meuLLigM2NU7loZAVM,iv:1Hbr4Q5SWZju2lCqd9aMMWb6SxIScicrn0Fwq2G+yBQ=,tag:qImJAj2deWegBWIxmMs5XQ==,type:str]
  AUTHENTIK_ENTRA_CLIENT_ID: ENC[AES256_GCM,data:NfMHvwR05vZYnjyoZNSoXX5ZzMQlqIBPsqr0t7DxdNMYMThU,iv:AmxywrH/R/Nvf/5Tf/+MEWcWdWgcC70Ac5rTaUk++K8=,tag:U3npMvnPqkS6x0Eo6gPjLQ==,type:str]
  AUTHENTIK_ENTRA_CLIENT_SECRET: ENC[AES256_GCM,data:y1JD0flSsK6sLSzTtNjCt+BG+DhjfSsiTI+RjSd3bO1i1e8dy1Lnig==,iv:9x10jim5pnVK/7qXCy+jE6Jh/sFdPMr4emAd6317dgA=,tag:tJaxc8RTDcyMR54Lf660Bw==,type:str]
sops:
  age:
    - recipient: age1metxlry78wefrmm5ny2zjavtucsmdvw2r3ctexu6h05ak4x2vc7qa02drd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQzVGNmhrWC96ME5PLytT
        UFBFVHBwTExCa1hsMTU1b3ZxUW8yMmpSbkVvCndtbjhta0RFbkNoak8wcVNvb0F5
        dmpCQTVWRndVZ2tRTm9xa2xrRFZsTFkKLS0tIGpRNWxsNmgrbnhGRUdsdG9USVVz
        M2ZUVDRUekpTVjczTVJzT0xvMjloK3cK540sVdykxjM5/aclh+y1fFF94VdHRCuX
        Eu8K+B1zo0O71KmdcvHSFE8FllX9v1pLPO46MIPyLleQz1UZ/Gs1tQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-10-04T11:18:03Z"
  mac: ENC[AES256_GCM,data:3mLdZpI4wYPibIC7vRgXlNPPP6RBNJfPGI3mjCCCzJXS+br6XYAgmDNCFq/Y0EwxMgThDOGnwcqzoBP4CDE0JmJGINtGXer1tKjBuiBIdM2nM3CO6fNuTUZ7DJcWkBg2DqRCbRjIn9qmGBjmEwVjv40lNq2u+YjPQVNPPagUWrE=,iv:X1myOzZgsYUahdq0Zhy0aCxVZejNER8CETw8VloWeG8=,tag:8rFqSjPHJ3YkpqqtuanSKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
