---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cachyos-7900xtx
  namespace: network
  annotations:
    prox-ops.io/dns-scope: unifi-static
spec:
  endpoints:
    - dnsName: cachyos-7900xtx.homelab0.org
      recordType: A
      targets: ["10.20.65.119"]
