apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-unas
spec:
  capacity:
    storage: 50Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
    - hard
    - noatime
  nfs:
    server: ENC[AES256_GCM,data:lPRi3VMxzQKNnql5,iv:aQkQnQ1VtC8yB0vhBsX439nMpzwaXvS0hzZvflWgtDA=,tag:/aHC8DRUvUPFChaN3ppQQA==,type:str]
    path: ENC[AES256_GCM,data:o107fMdfJBjkj/+3WOCMqi27cN5Y,iv:brUJ/jwx2jsfH4WzWuF9GZzX8Sy7097eddBvWMsmTUw=,tag:PWuAyMKTdo80wSxQrZEdFw==,type:str]
  claimRef:
    name: plex-media
    namespace: media
sops:
  age:
    - recipient: age1metxlry78wefrmm5ny2zjavtucsmdvw2r3ctexu6h05ak4x2vc7qa02drd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRDUxdGFXTE1GUVgrZHdG
        ejBFVDdRWHorUEhINHJSZFpLNmJ1TVZkandnCm5LR01IOFVCZC84T0M3ODY5RWxM
        bzFGNDJncGo3SmloV1EzSE10RGdXSUEKLS0tIGlRSVhhdDZtOXE0NHZFeVJTcW12
        M2dDTlVtaG1pK0VlK1VrQUYzdXB2aDAKP7lGmGDKJ8VXAp0eL2AWCgR7LGpoWOt1
        axn7dFlWmFxs4zKVqNnHCSjsgZ3LPHlFyHwRge2kOIkdBSdF/89B5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-27T07:28:39Z"
  mac: ENC[AES256_GCM,data:ZtpIDhXcAhUPqPeqTNTm1ke6Zw4tGdJB4VtunM8Lgh7Ciu7/IUrZhEIQm9TQrZneLdMZZ70KMdQYBWzbHMehk0RD/CTSkMv91FLJY8SHDnzRwGD6NUUnrtFGFTp8A4tTzHclKHNYssSPb5/w8hVxktRgJk/y3gyhZkv1tTtt87c=,iv:ygEidyj6LOVPenafhukxPnxF1+pWCYZCWH/bnwidkNQ=,tag:L5lnaJUExcohcaBIM8tzZQ==,type:str]
  encrypted_regex: ^(server|path)$
  mac_only_encrypted: true
  version: 3.11.0
