apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-media-unas
spec:
  capacity:
    storage: 50Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
    - hard
    - noatime
  nfs:
    server: ENC[AES256_GCM,data:KJa/9UAYoNGqw+C6,iv:74zuwnMq6OE556cA4WVkU1m20VwFEQL0WszVvb2UNh0=,tag:mKXiZXCXRD6TGFBAgEyd5g==,type:str]
    path: ENC[AES256_GCM,data:bXPFbleGuJ5CG79XGm3ZwtEJ8QAy,iv:j7UoYx1aV2NRgb77JCdpE+0n9oiZjozviDxS6kZzmR8=,tag:vwIzNRkIP/4aZ8OZ3SMwDQ==,type:str]
  claimRef:
    name: downloads-media
    namespace: downloads
sops:
  age:
    - recipient: age1metxlry78wefrmm5ny2zjavtucsmdvw2r3ctexu6h05ak4x2vc7qa02drd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSmJsM0hibk9TbnBWbXRj
        UXE0b0pURy95eGovZ0xPZmJoSkt6SXEvY1EwClN6MXlzU0hRdTA5VzZ4bUpuSERn
        NFlWQ3hsbjF0MlU0endKOHhGaVkwb2sKLS0tIE1QMWE4STVYSlZuTUVCOFAxT29l
        NUhabWJhcUhZOWsydVU4YTk4V1dSMjgKIpaDBtV3EIOTruQAMAlKhLGEhAbU8/eM
        lYk6v/ho6UJNOztoulamUqNMv/SN3uP0NhS+Qf/tNnI5DdG2cZkIlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-27T07:28:39Z"
  mac: ENC[AES256_GCM,data:ROxQUN9XtH0BVsXhddJQYNfDxoXMYFpxrAt/4FLNScs/7YsmVrOZ/Jqqh1zdiFfySt1gFbZn+kJz40m69TBv8R8axZiSdNJoKaS0d6gTxBN7Gi+bSeN3ada2M2tCpG756pMZU6fA2eBHKTwXmrUccSGEVYOTlWIrSTsNxagnVR0=,iv:Vk3w+g3EfaJ8kKSxGnEVNhV6rPQYsQtwEcw88J9kELU=,tag:3dHreqCizCasclLnDCumnQ==,type:str]
  encrypted_regex: ^(server|path)$
  mac_only_encrypted: true
  version: 3.11.0
