#!/usr/bin/env python3
"""Render the aggregate-only Hindsight runnable-backlog function DDL.

The function returns scripts/hindsight-queue-backlog.py build_sql(256) byte for
byte, minus its terminating semicolon, so the database function and the CLI
cannot drift apart. Callers pass nothing: no SQL, schema, bank, filter or bound.
The rendered file is not referenced by any Kustomization.
"""
import argparse
import importlib.util
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CANONICAL = ROOT / 'scripts/hindsight-queue-backlog.py'
MANIFEST = ROOT / 'kubernetes/apps/ai/hermes-hindsight/app/hindsight.yaml'
TARGET = ROOT / 'kubernetes/apps/database/hindsight-backlog/app/runnable-backlog.sql'

# The claim predicate is qualified against exactly this image and migration
# head. An equal Alembic revision alone does not prove the claim code is
# unchanged, so an image bump must fail --check until the predicate is
# requalified and both values are updated together.
SUPPORTED_API_IMAGE = ('ghcr.io/vectorize-io/hindsight-api:0.9.2'
                       '@sha256:7b14a1f4062252992d0176758753615e0a2071d9a269995be007be223ab01812')
# Head migration of v0.9.2: https://github.com/vectorize-io/hindsight/blob/v0.9.2/hindsight-api-slim/
# hindsight_api/alembic/versions/d1e2f3a4b5c6_drop_v1_mental_model_structured_content.py
# An authorised read-only qualification found it as both the pinned image's installed
# migration head and the live database revision.
SUPPORTED_SCHEMA_HEAD = 'd1e2f3a4b5c6'
MAX_GROUPS = 256
UNKNOWN_SQLSTATE = 'HSB01'
REQUIRED_COLUMNS = ('operation_id', 'bank_id', 'operation_type', 'status', 'task_payload',
                    'serialization_key', 'created_at', 'next_retry_at', 'worker_id')
API_IMAGE_PATH = ('spec', 'values', 'api', 'image')
# A tripwire, not the boundary. The boundaries are the byte-equal reviewed canonical
# query, STABLE (PostgreSQL rejects writes at run time) and read-only callers; this
# only stops an obviously side-effecting token in a drifted query from rendering.
FORBIDDEN = re.compile(r'\b(execute|perform|insert|update|delete|merge|copy|truncate|lock|share|notify|listen|'
                       r'set|reset|call|create|drop|alter|grant|revoke|set_config|current_setting|nextval|setval|'
                       r'dblink\w*|lo_\w+|query_to_\w+|pg_(sleep|advisory|notify|terminate|cancel|read|ls|stat_file|'
                       r'stat_reset|reload|file|write|logical|replication|promote|switch_wal|rotate)\w*)\b')

FUNCTION_BODY = """BEGIN
 -- plpgsql binds relations when the body runs and records no pg_depend rows on
 -- them, so upstream migrations stay unblocked. A shape or revision the predicate
 -- was not qualified for is reported as the fixed unknown, never as zero.
 IF (SELECT count(*) FROM pg_class WHERE relkind IN ('r', 'p') AND oid IN (to_regclass('public.async_operations'),
       to_regclass('public.banks'), to_regclass('public.alembic_version'))) <> 3
    OR (SELECT count(*) FROM pg_attribute WHERE attrelid = to_regclass('public.async_operations')
          AND attnum > 0 AND NOT attisdropped AND attname = ANY (ARRAY[{columns}]::name[])) <> {column_count}
    OR NOT EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = to_regclass('public.banks')
          AND attnum > 0 AND NOT attisdropped AND attname = 'bank_id')
    OR (SELECT count(*) FROM public.alembic_version) <> 1
    OR NOT EXISTS (SELECT 1 FROM public.alembic_version WHERE version_num = '{schema_head}') THEN
  RAISE EXCEPTION USING ERRCODE = '{sqlstate}', MESSAGE = 'hindsight backlog unknown';
 END IF;
 RETURN (
{query}
 );
EXCEPTION WHEN OTHERS THEN
 -- Fixed code and message only: no source error text or row value escapes.
 -- Cancellation (statement_timeout) is not OTHERS and still surfaces as 57014.
 RAISE EXCEPTION USING ERRCODE = '{sqlstate}', MESSAGE = 'hindsight backlog unknown';
END
"""

DDL = """-- Generated by scripts/hindsight-backlog-function.py --write; do not edit.
-- Not referenced by any Kustomization: nothing applies this file yet.
-- Qualified for {image}
-- at Alembic head {schema_head}. Apply as the hindsight role (SET ROLE
-- hindsight is enough); the guards refuse any other owner and roll back on drift.
BEGIN;
SET LOCAL search_path = pg_catalog, pg_temp;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';
DO $guard$
BEGIN
 IF current_user <> 'hindsight' OR (SELECT rolsuper FROM pg_roles WHERE rolname = current_user) THEN
  RAISE EXCEPTION 'apply as the non-superuser hindsight role';
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'hindsight_backlog_metrics' AND NOT rolsuper
                AND NOT rolcreaterole AND NOT rolcreatedb AND NOT rolreplication AND NOT rolbypassrls)
    OR EXISTS (SELECT 1 FROM pg_auth_members m JOIN pg_roles r ON r.oid IN (m.member, m.roleid)
               WHERE r.rolname = 'hindsight_backlog_metrics') THEN
  RAISE EXCEPTION 'hindsight_backlog_metrics must exist with no extra authority, members or memberships';
 END IF;
 IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'hindsight_metrics' AND nspowner <> 'hindsight'::regrole)
    OR EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
               WHERE n.nspname = 'hindsight_metrics')
    OR EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
               WHERE n.nspname = 'hindsight_metrics')
    OR EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
               WHERE n.nspname = 'hindsight_metrics' AND (p.proname <> 'runnable_backlog' OR p.pronargs <> 0
                     OR p.proowner <> 'hindsight'::regrole)) THEN
  RAISE EXCEPTION 'hindsight_metrics holds a relation, type or function this file did not generate';
 END IF;
END
$guard$;
CREATE SCHEMA IF NOT EXISTS hindsight_metrics AUTHORIZATION hindsight;
CREATE OR REPLACE FUNCTION hindsight_metrics.runnable_backlog()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SECURITY DEFINER
 SET search_path = pg_catalog, pg_temp
AS $function$
{body}$function$;
REVOKE ALL ON SCHEMA hindsight_metrics FROM PUBLIC;
REVOKE ALL ON FUNCTION hindsight_metrics.runnable_backlog() FROM PUBLIC;
GRANT USAGE ON SCHEMA hindsight_metrics TO hindsight_backlog_metrics;
GRANT EXECUTE ON FUNCTION hindsight_metrics.runnable_backlog() TO hindsight_backlog_metrics;
DO $verify$
DECLARE
 fn oid := to_regprocedure('hindsight_metrics.runnable_backlog()');
BEGIN
 IF fn IS NULL
    OR (SELECT nspowner FROM pg_namespace WHERE nspname = 'hindsight_metrics') <> 'hindsight'::regrole
    OR ARRAY(SELECT a::text FROM pg_namespace n, unnest(n.nspacl) a WHERE n.nspname = 'hindsight_metrics'
             ORDER BY a::text COLLATE "C") <> ARRAY['hindsight=UC/hindsight', 'hindsight_backlog_metrics=U/hindsight']
    OR ARRAY(SELECT a::text FROM pg_proc p, unnest(p.proacl) a WHERE p.oid = fn
             ORDER BY a::text COLLATE "C") <> ARRAY['hindsight=X/hindsight', 'hindsight_backlog_metrics=X/hindsight']
    OR NOT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid = p.prolang
                   WHERE p.oid = fn AND p.proowner = 'hindsight'::regrole AND p.prosecdef AND p.provolatile = 's'
                     AND NOT p.proretset AND p.prorettype = 'jsonb'::regtype AND l.lanname = 'plpgsql'
                     AND p.proconfig = ARRAY['search_path=pg_catalog, pg_temp'])
    OR EXISTS (SELECT 1 FROM pg_depend WHERE classid = 'pg_proc'::regclass AND objid = fn
               AND refclassid = 'pg_class'::regclass) THEN
  RAISE EXCEPTION 'hindsight_metrics.runnable_backlog ownership, ACL or attributes are not as generated';
 END IF;
END
$verify$;
COMMIT;
"""


class RenderError(Exception):
    pass


def load_canonical(path=CANONICAL):
    spec = importlib.util.spec_from_file_location('hindsight_queue_backlog', path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def canonical_query(module):
    if module.DEFAULT_MAX_GROUPS != MAX_GROUPS:
        raise RenderError('canonical aggregate bound changed; requalify the function')
    sql = module.build_sql(MAX_GROUPS)
    if not sql.endswith(';') or sql.count(';') != 1 or '$' in sql:
        raise RenderError('canonical query is not a single statement safe to embed')
    return sql[:-1]


def function_body(query):
    columns = ', '.join(f"'{name}'" for name in REQUIRED_COLUMNS)
    body = FUNCTION_BODY.format(columns=columns, column_count=len(REQUIRED_COLUMNS), query=query,
                                schema_head=SUPPORTED_SCHEMA_HEAD, sqlstate=UNKNOWN_SQLSTATE)
    if FORBIDDEN.search(body.lower()):
        raise RenderError('function body contains a statement a read-only aggregate never needs')
    return body


def render(module=None):
    query = canonical_query(module or load_canonical())
    return DDL.format(image=SUPPORTED_API_IMAGE, schema_head=SUPPORTED_SCHEMA_HEAD, body=function_body(query))


def manifest_api_image(text):
    """repository:tag of the HelmRelease's api.image block, located by key path, never by searching for a tag."""
    found, path = {}, []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith('#') or stripped == '---':
            continue
        key, separator, value = stripped.partition(':')
        if not separator:
            continue
        indent = len(line) - len(line.lstrip(' '))
        while path and path[-1][0] >= indent:
            path.pop()
        path.append((indent, key))
        keys = tuple(name for _, name in path)
        if keys[:-1] == API_IMAGE_PATH and keys[-1] in ('repository', 'tag'):
            if keys[-1] in found:
                return None
            found[keys[-1]] = value.strip().strip('"\'')
    if set(found) != {'repository', 'tag'}:
        return None
    return f"{found['repository']}:{found['tag']}"


def render_checked():
    """The render, refused unless the HelmRelease still pins the qualified API image."""
    if manifest_api_image(MANIFEST.read_text()) != SUPPORTED_API_IMAGE:
        raise RenderError('pinned hindsight-api image is not the qualified one; requalify the predicate first')
    return render()


def check(path):
    try:
        expected = render_checked().encode()
    except RenderError as error:
        return str(error)
    try:
        actual = pathlib.Path(path).read_bytes()
    except OSError:
        return 'generated DDL missing; run --write'
    return None if actual == expected else 'generated DDL is stale or hand-edited; run --write'


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--check', metavar='PATH', help='fail unless PATH is the exact render')
    mode.add_argument('--write', action='store_true', help='regenerate the one committed DDL target')
    args = parser.parse_args(argv)
    # An empty --check path must fail the check, never fall through to --write.
    if args.check is not None:
        problem = check(args.check)
    else:
        try:
            ddl = render_checked()
        except RenderError as error:
            problem = str(error)
        else:
            TARGET.parent.mkdir(parents=True, exist_ok=True)
            TARGET.write_text(ddl)
            problem = None
    if problem:
        print(problem, file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
