apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-media-unas
spec:
  capacity:
    storage: 50Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
    - hard
    - noatime
  nfs:
    server: ENC[AES256_GCM,data:vUJU+T3to78IbML7,iv:QM9cebI/WANXOPMjaWZWVWWRmos8pdqfb6MLTXL9Pg4=,tag:ftDN/Ur9M171rQ+0MSCa4g==,type:str]
    path: ENC[AES256_GCM,data:MVSw6EznyotP26i8EiaB3crg0gZs,iv:oc2mThY0n3wsAokuFGheGgNhYzw7kZTK7uS630yuhN0=,tag:/ByARhWBUGQEe4BQE/fyPQ==,type:str]
  claimRef:
    name: arr-media
    namespace: media
sops:
  age:
    - recipient: age1metxlry78wefrmm5ny2zjavtucsmdvw2r3ctexu6h05ak4x2vc7qa02drd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdXRtZDg3UHVKbUxVUFI1
        bnVuOVljc2trZDVDaVBSS0Q1bXZnNk9wZUVVCjRzTHI1eklKS29wbTBrMFU1MHV1
        T0pXN3FBSHhxZFpwck5jWllqdHg2RWcKLS0tIGNaSmVFQjIyN3YvV3pTUnRPWEFE
        VDlQUXJpb2FzOUJ1S0JFbkJ0bzdLQ00KPWXkaCCSJCzNCJ7vdnoq6J+V2+T66m3n
        mjSEZVQCetXfAxQh7RLnMcDc/VhUaaczrKK15M/ImhzTtae80UBOxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-27T07:28:39Z"
  mac: ENC[AES256_GCM,data:WrmlTqCfTR5mcNFGsoReDHj0Ln9m8FmwnLdbxEiCi3wO9IdzhgC7RgARXksDpLmRnqURFFYB8TlLpfSSoa3lDxLaDJ6RyTr5QSy1my2SQOhpI/siZou3S5CEjgkdkT//gTREXzzJKHeOY/PBEKVAwN372+izGSF01Fw0BgqoVgM=,iv:KA902Lx/eNY2rVEJQPlbYzP3I54xeRKuiE63RHCQYFA=,tag:V77nVhpdvHik8ri7493nAg==,type:str]
  encrypted_regex: ^(server|path)$
  mac_only_encrypted: true
  version: 3.11.0
