---
apiVersion: v1
kind: Namespace
metadata:
  name: health
  labels:
    kubernetes.io/metadata.name: health
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
