---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: notes

resources:
  - ./namespace.yaml
  - ./obsidian/storage/ks.yaml  # Storage with prune: false - MUST come before obsidian
  - ./obsidian/ks.yaml
