---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./sources.yaml
  - ./externalsecrets.yaml
  - ./hindsight.yaml
  - ./hermes.yaml
  - ./access.yaml
  - ./networkpolicy.yaml
